sudo: false
language: node_js
node_js:
- 7
cache:
  directories:
  - node_modules
notifications:
  email: false
addons:
  sauce_connect: true

install:
- npm prune && npm install

before_script:
- npm start

script:
- npm run test:e2e
